// Country list for foreign-national ID capture. South Africa is intentionally omitted
// (SA nationals use the SA ID path). Ordered with common origins near the top.
export const COUNTRIES: string[] = [
  'Zimbabwe',
  'Mozambique',
  'Lesotho',
  'Eswatini',
  'Botswana',
  'Namibia',
  'Malawi',
  'Zambia',
  'Nigeria',
  'Ghana',
  'Kenya',
  'Democratic Republic of the Congo',
  'Angola',
  'Tanzania',
  'Ethiopia',
  'Somalia',
  'Cameroon',
  'Uganda',
  'Rwanda',
  'Burundi',
  'Senegal',
  'Ivory Coast',
  'Egypt',
  'Morocco',
  'Algeria',
  'Tunisia',
  'Sudan',
  'Bangladesh',
  'Pakistan',
  'India',
  'China',
  'Philippines',
  'Indonesia',
  'United Kingdom',
  'Germany',
  'France',
  'Netherlands',
  'Portugal',
  'Italy',
  'Spain',
  'United States',
  'Canada',
  'Brazil',
  'Australia',
  'Afghanistan',
  'Albania',
  'Argentina',
  'Austria',
  'Belgium',
  'Bulgaria',
  'Chile',
  'Colombia',
  'Croatia',
  'Cuba',
  'Denmark',
  'Ecuador',
  'Finland',
  'Greece',
  'Hungary',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Japan',
  'Jordan',
  'Lebanon',
  'Malaysia',
  'Mexico',
  'Nepal',
  'New Zealand',
  'Norway',
  'Peru',
  'Poland',
  'Romania',
  'Russia',
  'Saudi Arabia',
  'Serbia',
  'Singapore',
  'South Korea',
  'Sri Lanka',
  'Sweden',
  'Switzerland',
  'Syria',
  'Thailand',
  'Turkey',
  'Ukraine',
  'United Arab Emirates',
  'Venezuela',
  'Vietnam',
  'Yemen',
];
